[package]
name = "epoch"
version = "0.1.0"
authors = ["vince <vince.siu4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
structopt = "0.3.14"